# Generated by Django 5.2.1 on 2025-05-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='dialy_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
