# Generated by Django 5.2.1 on 2025-05-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_attendance_dialy_hours_attendance_total_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Graphic Designer', 'Graphic Designer'), ('Digital Marketing', 'Digital Marketing')]),
        ),
    ]
