# Generated by Django 5.2.1 on 2025-06-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='dialy_hours',
            new_name='daily_hours',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Graphic Designer', 'Graphic Designer'), ('Digital Marketing', 'Digital Marketing')], max_length=50),
        ),
    ]
