# Generated by Django 5.2.1 on 2025-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_dialy_hours_attendance_daily_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='daily_hours',
            field=models.CharField(default='0:00', max_length=5),
        ),
    ]
